// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use env vars if available, otherwise fall back to hardcoded public keys
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://svmbveclvswlufdeumgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2bWJ2ZWNsdnN3bHVmZGV1bWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NTAyMjUsImV4cCI6MjA4NTMyNjIyNX0.PFmXgA6UhPr48FBvTkJwMdjDr9M-YapI2Kkm3NHjt9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);